site_name: Django Pyscript
theme:
    name: material
markdown_extensions:
    - admonition
    - markdown_blockdiag:
        format: svg
    - markdown_include.include
    - codehilite
plugins:
    - search