# Generated by Django 3.1.1 on 2020-09-09 16:23

from django.db import migrations
import djpyscript.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_testmodel_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='script2',
            field=djpyscript.fields.PyScriptField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
